version: 2
jobs:
  build:
    docker:
      - image: celohq/node8:gcloud
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "strategy/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd strategy && yarn install && yarn run tsc

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "strategy/package.json" }}
      # Check that things compile
      - run: cd sdk && yarn && yarn run build && yarn run tsc

